# Generated by Django 5.0.1 on 2024-02-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_user_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
    ]
