# Generated by Django 4.2.10 on 2024-02-07 09:28

from django.db import migrations
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', profiles.models.UserManager()),
            ],
        ),
    ]
