version: "3"

services:

  api:
    build: .
    command: python manage.py runserver
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  redis:
    image: redis
    ports:
      - 6379:6379
  celery:
    image: celery
    ports:
      - 5672:5672

volumes:
  postgres_data:
